export const ADD_BURGER_CONSTRUCTOR_INGREDIENT: 'ADD_BURGER_CONSTRUCTOR_INGREDIENT' = 'ADD_BURGER_CONSTRUCTOR_INGREDIENT';
export const DELETE_BURGER_CONSTRUCTOR_INGREDIENT: 'DELETE_BURGER_CONSTRUCTOR_INGREDIENT' = 'DELETE_BURGER_CONSTRUCTOR_INGREDIENT';
export const UPDATE_BURGER_CONSTRUCTOR_INGREDIENTS_LIST: 'UPDATE_BURGER_CONSTRUCTOR_INGREDIENTS_LIST' = 'UPDATE_BURGER_CONSTRUCTOR_INGREDIENTS_LIST';
export const DELETE_BURGER_CONSTRUCTOR_INGREDIENTS_LIST: 'DELETE_BURGER_CONSTRUCTOR_INGREDIENTS_LIST' = 'DELETE_BURGER_CONSTRUCTOR_INGREDIENTS_LIST';

export const ADD_INGREDIENT_DETAILS: 'ADD_INGREDIENT_DETAILS' = 'ADD_INGREDIENT_DETAILS';
export const DELETE_INGREDIENT_DETAILS: 'DELETE_INGREDIENT_DETAILS' = 'DELETE_INGREDIENT_DETAILS';

export const UPDATE_ORDER_DETAILS: 'UPDATE_ORDER_DETAILS' = 'UPDATE_ORDER_DETAILS';

export const GET_BURGER_INGREDIENTS_REQUEST: 'GET_BURGER_INGREDIENTS_REQUEST' = 'GET_BURGER_INGREDIENTS_REQUEST';
export const GET_BURGER_INGREDIENTS_SUCCESS: 'GET_BURGER_INGREDIENTS_SUCCESS' = 'GET_BURGER_INGREDIENTS_SUCCESS';
export const GET_BURGER_INGREDIENTS_ERROR: 'GET_BURGER_INGREDIENTS_ERROR' = 'GET_BURGER_INGREDIENTS_ERROR';
export const BURGER_INGREDIENT_COUNTER_INCREMENT: 'BURGER_INGREDIENT_COUNTER_INCREMENT' = 'BURGER_INGREDIENT_COUNTER_INCREMENT';
export const BURGER_INGREDIENT_COUNTER_DECREMENT: 'BURGER_INGREDIENT_COUNTER_DECREMENT' = 'BURGER_INGREDIENT_COUNTER_DECREMENT';
export const BURGER_INGREDIENT_COUNTER_RESET: 'BURGER_INGREDIENT_COUNTER_RESET' = 'BURGER_INGREDIENT_COUNTER_RESET';

export const UPDATE_ORDER_DETAILS_REQUEST: 'UPDATE_ORDER_DETAILS_REQUEST' = 'UPDATE_ORDER_DETAILS_REQUEST';
export const UPDATE_ORDER_DETAILS_SUCCESS: 'UPDATE_ORDER_DETAILS_SUCCESS' = 'UPDATE_ORDER_DETAILS_SUCCESS';
export const UPDATE_ORDER_DETAILS_ERROR: 'UPDATE_ORDER_DETAILS_ERROR' = 'UPDATE_ORDER_DETAILS_ERROR';

export const POST_ORDER_REQUEST: 'POST_ORDER_REQUEST' = 'POST_ORDER_REQUEST';
export const POST_ORDER_SUCCESS: 'POST_ORDER_SUCCESS' = 'POST_ORDER_SUCCESS';
export const POST_ORDER_ERROR: 'POST_ORDER_ERROR' = 'POST_ORDER_ERROR';
